// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dndudgqkoiybenqnavoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZHVkZ3Frb2l5YmVucW5hdm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDkwODMsImV4cCI6MjA2MDAyNTA4M30.fix5Vo1a06P-uN0bhj5y5og3QIg4NcZ-tM5ZGWX0aRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);